language: node_js
node_js:
- '8'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
install:
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "dgDcXdlQGsWx2m69Jq3NiMQgdbYugyjp6E2N6dhUf0a8jZuJSUZ4CIUYAB0czF/+Lf04nQIxZSFceYmG11Jh/bubNJgqs/9rm+gfLwHGYY7BfTWForQhf4sxx//qYe/Vg39CUhDTze3SYAuiJVVppGQRKcnJQ4LFi2A879C26e1rnNMFQ45fZMjjMFH0I9AdqS2qbJop0UMLVD/7Txz8mmUbBBJCa/EXtdLZkBua5vJmSytcJQxuYfM0qo7Yk2zPWUC46kPXyvMf9b4JvBk5+y88v5D2eTYrvOQrtVWSQD0i07gj6s0jGezsyYMkTF8yxBTAz2ObCVzC5QFSuzZmFMbfdZkVQFaoupza5U2LdBPjs4uK/E2JjVRZVxFBzncx6l/IlhD2ox0PwUTa8GPIMomZm+GPGF65JtTLdbU+ZIBiqiE8UDyesXLNT5z3pJI3HPmaml/Jxj1MrxkZzW1QjfraBlol7lYIeWS06OcLAy0FnOa+qbzfWFrT2iiYm7F/n7yDhx85yY0svUSqAsFJDQnhhl1zb2SR6TBEX0hIEZ0Mj0NH5kz1YnoD5AABi8wnoWkCzhIJI+x5lr5g27ezXl/3/U2EBpbQ5C7mhc1N+5Bm3EqdmxUHJdw0Ouf2J/hTzSeWVg6lagEqsjM2TnbNkML6rAT9k/k95ppKBL0nShg="
